flags:
  gi-webkit2:
    overloaded-properties: false
    overloaded-methods: false
    overloaded-signals: false
  gi-gio:
    overloaded-properties: false
    overloaded-methods: false
    overloaded-signals: false
  gi-atk:
    overloaded-properties: false
    overloaded-methods: false
    overloaded-signals: false
  gi-cairo:
    overloaded-properties: false
    overloaded-methods: false
    overloaded-signals: false
  gi-glib:
    overloaded-properties: false
    overloaded-methods: false
    overloaded-signals: false
  gi-gtk:
    overloaded-properties: false
    overloaded-methods: false
    overloaded-signals: false
  gi-gdk:
    overloaded-properties: false
    overloaded-methods: false
    overloaded-signals: false
  gi-gtksource:
    overloaded-properties: false
    overloaded-methods: false
    overloaded-signals: false
  gi-gobject:
    overloaded-properties: false
    overloaded-methods: false
    overloaded-signals: false
  gi-pango:
    overloaded-properties: false
    overloaded-methods: false
    overloaded-signals: false
  gi-soup:
    overloaded-properties: false
    overloaded-methods: false
    overloaded-signals: false
  gi-javascriptcore:
    overloaded-properties: false
    overloaded-methods: false
    overloaded-signals: false
  gi-gdkpixbuf:
    overloaded-properties: false
    overloaded-methods: false
    overloaded-signals: false
extra-package-dbs: []
packages:
- '.'
- vendor/leksah-server
- vendor/ltk
- vendor/haskellVCSGUI/vcsgui
- vendor/haskellVCSWrapper/vcswrapper
- location:
    git: https://github.com/basvandijk/haddock.git
    commit: f4c5e46ded05a4b8884f5ad6f3102f79ff3bb127
  subdirs:
  - haddock-api
extra-deps:
- binary-shared-0.8.3
- gi-atk-2.0.12
- gi-cairo-1.0.12
- gi-gdk-3.0.12
- gi-gdkpixbuf-2.0.12
- gi-gio-2.0.12
- gi-glib-2.0.12
- gi-gobject-2.0.12
- gi-gtk-3.0.14
- gi-gtk-hs-0.3.4.2
- gi-gtksource-3.0.13
- gi-javascriptcore-4.0.12
- gi-pango-1.0.13
- gi-soup-2.4.12
- gi-webkit2-4.0.12
resolver: lts-8.12
